// src/components/features/vehicles/constants/brands.js
export const CAR_BRANDS = [
  { value: "mercedes", label: "Mercedes-Benz" },
  { value: "bmw", label: "BMW" },
  { value: "audi", label: "Audi" },
  { value: "toyota", label: "Toyota" },
  { value: "hyundai", label: "Hyundai" },
  { value: "kia", label: "KIA" },
  { value: "volkswagen", label: "Volkswagen" },
  { value: "nissan", label: "Nissan" },
  { value: "honda", label: "Honda" },
  { value: "ford", label: "Ford" },
  { value: "chevrolet", label: "Chevrolet" },
  { value: "lada", label: "LADA" },
  { value: "mazda", label: "Mazda" },
  { value: "mitsubishi", label: "Mitsubishi" },
  { value: "skoda", label: "Škoda" },
  { value: "renault", label: "Renault" },
  { value: "peugeot", label: "Peugeot" },
  { value: "citroen", label: "Citroën" },
  { value: "opel", label: "Opel" },
  { value: "seat", label: "SEAT" },
  { value: "jeep", label: "Jeep" },
  { value: "land_rover", label: "Land Rover" },
  { value: "porsche", label: "Porsche" },
  { value: "lexus", label: "Lexus" },
  { value: "infiniti", label: "Infiniti" },
];

export const CAR_MODELS = {
  mercedes: [
    { value: "c_class", label: "C-Class" },
    { value: "e_class", label: "E-Class" },
    { value: "s_class", label: "S-Class" },
    { value: "glc", label: "GLC" },
    { value: "gla", label: "GLA" },
    { value: "gle", label: "GLE" },
    { value: "gls", label: "GLS" },
    { value: "a_class", label: "A-Class" },
    { value: "b_class", label: "B-Class" },
    { value: "cla", label: "CLA" },
    { value: "cls", label: "CLS" },
    { value: "g_class", label: "G-Class" },
  ],
  bmw: [
    { value: "1_series", label: "1 Series" },
    { value: "3_series", label: "3 Series" },
    { value: "5_series", label: "5 Series" },
    { value: "7_series", label: "7 Series" },
    { value: "x1", label: "X1" },
    { value: "x3", label: "X3" },
    { value: "x5", label: "X5" },
    { value: "x7", label: "X7" },
    { value: "z4", label: "Z4" },
    { value: "i3", label: "i3" },
    { value: "i8", label: "i8" },
  ],
  audi: [
    { value: "a3", label: "A3" },
    { value: "a4", label: "A4" },
    { value: "a6", label: "A6" },
    { value: "a8", label: "A8" },
    { value: "q3", label: "Q3" },
    { value: "q5", label: "Q5" },
    { value: "q7", label: "Q7" },
    { value: "q8", label: "Q8" },
    { value: "tt", label: "TT" },
    { value: "r8", label: "R8" },
  ],
  toyota: [
    { value: "camry", label: "Camry" },
    { value: "corolla", label: "Corolla" },
    { value: "prius", label: "Prius" },
    { value: "rav4", label: "RAV4" },
    { value: "highlander", label: "Highlander" },
    { value: "land_cruiser", label: "Land Cruiser" },
    { value: "prado", label: "Prado" },
    { value: "yaris", label: "Yaris" },
    { value: "avensis", label: "Avensis" },
  ],
  hyundai: [
    { value: "accent", label: "Accent" },
    { value: "elantra", label: "Elantra" },
    { value: "sonata", label: "Sonata" },
    { value: "tucson", label: "Tucson" },
    { value: "santa_fe", label: "Santa Fe" },
    { value: "creta", label: "Creta" },
    { value: "i30", label: "i30" },
    { value: "ix35", label: "ix35" },
  ],
  kia: [
    { value: "rio", label: "Rio" },
    { value: "cerato", label: "Cerato" },
    { value: "optima", label: "Optima" },
    { value: "sportage", label: "Sportage" },
    { value: "sorento", label: "Sorento" },
    { value: "picanto", label: "Picanto" },
    { value: "soul", label: "Soul" },
  ],
  volkswagen: [
    { value: "golf", label: "Golf" },
    { value: "passat", label: "Passat" },
    { value: "jetta", label: "Jetta" },
    { value: "tiguan", label: "Tiguan" },
    { value: "touareg", label: "Touareg" },
    { value: "polo", label: "Polo" },
    { value: "arteon", label: "Arteon" },
  ],
  nissan: [
    { value: "altima", label: "Altima" },
    { value: "sentra", label: "Sentra" },
    { value: "maxima", label: "Maxima" },
    { value: "qashqai", label: "Qashqai" },
    { value: "x_trail", label: "X-Trail" },
    { value: "patrol", label: "Patrol" },
    { value: "murano", label: "Murano" },
  ],
  honda: [
    { value: "civic", label: "Civic" },
    { value: "accord", label: "Accord" },
    { value: "cr_v", label: "CR-V" },
    { value: "pilot", label: "Pilot" },
    { value: "fit", label: "Fit" },
    { value: "odyssey", label: "Odyssey" },
  ],
  ford: [
    { value: "focus", label: "Focus" },
    { value: "fiesta", label: "Fiesta" },
    { value: "escape", label: "Escape" },
    { value: "explorer", label: "Explorer" },
    { value: "f_150", label: "F-150" },
    { value: "mustang", label: "Mustang" },
  ],
};
